server:
  port: 8080

spring:
  application:
    name: sorisoop-backend
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      image:
        options:
          model: dall-e-3

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false
