server:
  port: 8080

spring:
  application:
    name: sorisoop-backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      image:
        options:
          model: dall-e-3
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

billing:
  customer-key-secret: ${CUSTOMER_KEY_SECRET}
  secret-key: ${TOSS_SECRET_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}