spring:
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_HOST}/FREEPDB1
    username: ${ORACLE_DEV_USERNAME}
    password: ${ORACLE_DEV_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_LOCAL_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

rabbit:
  queue: fairytale.queue.dev
  exchange: fairytale.exchange
  routing-key: fairytale.create